language: php

branches:
  # Only test the master branch.
  only:
    - master

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0

sudo: false

cache:
  directories:
    - src

before_script:
  - composer install --prefer-dist

